# Generated by Django 4.0 on 2021-12-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='', max_length=50, verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
