# Generated by Django 4.0 on 2021-12-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouToUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Тебе к нам если',
                'verbose_name_plural': 'Тебе к нам если',
            },
        ),
    ]
