# Generated by Django 4.0 on 2021-12-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_youtous'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodToKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Полезно знать',
                'verbose_name_plural': 'Полезно знать',
            },
        ),
    ]
