# Generated by Django 4.0 on 2021-12-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_goodtoknow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodtoknow',
            options={'ordering': ['sorting'], 'verbose_name': 'Полезно знать', 'verbose_name_plural': 'Полезно знать'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sorting'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='youtous',
            options={'ordering': ['sorting'], 'verbose_name': 'Тебе к нам если', 'verbose_name_plural': 'Тебе к нам если'},
        ),
        migrations.AddField(
            model_name='goodtoknow',
            name='sorting',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='sorting',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtous',
            name='sorting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
