# Generated by Django 4.0 on 2021-12-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_goodtoknow_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sorting', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ты получишь',
                'verbose_name_plural': 'Ты получишь',
                'ordering': ['sorting'],
            },
        ),
    ]
