# Generated by Django 4.0 on 2022-01-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_youget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='img/galery/', verbose_name='Изображение')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Alt текст')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
