# Generated by Django 4.0 on 2022-01-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_galery'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='is_gif',
            field=models.BooleanField(default=False, verbose_name='Если GIF'),
        ),
    ]
