# Generated by Django 4.0 on 2022-01-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_galery_is_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='sorting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
