# Generated by Django 4.0 on 2022-01-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_galery_options_service_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='img/cleaning/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Слайдер ',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка'),
        ),
    ]
