# Generated by Django 4.0 on 2022-01-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_cleaningslider_alter_service_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaningslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
    ]
