# Generated by Django 4.0 on 2021-12-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_change_battery',
            field=models.BooleanField(default=False, verbose_name='Замена АКБ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_cleaning',
            field=models.BooleanField(default=False, verbose_name='Чистка наушников'),
        ),
    ]
